# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('usermail', models.EmailField(max_length=254)),
                ('userpass', models.CharField(max_length=20)),
            ],
        ),
    ]
