# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
