# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enabled',
        ),
    ]
